name: MATLAB build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Build an extension and test
        uses: matlab-actions/run-command@v2
        with:
          command: mex cppArrayMex.cpp; testcppArray
